version: '3.1'
services:
  app:
    container_name: test-app
    image: test-app
    build: ./
    ports:
      - "8092:8092"
    volumes:
      - "$PWD:/test"
#     depends_on:
#       - postgresqldb
#   postgresqldb:
#     image: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=task
